[package]
name = "workshop1"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.10"       # Para paralelismo de alto nivel
chrono = "0.4"       # Para medir tiempos
log = "0.4"
env_logger = "0.11"

[dev-dependencies]
criterion = "0.5"
